# Generated by Django 5.1.2 on 2024-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.FileField(null=True, upload_to='mydata/'),
        ),
    ]
