# Generated by Django 5.1.2 on 2024-10-28 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_message_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='data',
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('clear_by_sender', models.BooleanField(default=False)),
                ('clear_by_receiver', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
