# Generated by Django 5.1.2 on 2024-10-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_message_data_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
